ansible_user: user@domain.local
ansible_connection: winrm
ansible_winrm_scheme: http
ansible_port: 5985
ansible_winrm_transport: kerberos

ansible_become: yes
ansible_become_method: runas
ansible_become_user: SYSTEM

